import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Cobalt — interactive primary
        cobalt: {
          50:  "var(--cobalt-50)",
          100: "var(--cobalt-100)",
          200: "var(--cobalt-200)",
          300: "var(--cobalt-300)",
          400: "var(--cobalt-400)",
          500: "var(--cobalt-500)",
          600: "var(--cobalt-600)",
          700: "var(--cobalt-700)",
          800: "var(--cobalt-800)",
          900: "var(--cobalt-900)",
        },
        // Ink — deep navy neutrals
        ink: {
          100: "var(--ink-100)",
          200: "var(--ink-200)",
          300: "var(--ink-300)",
          400: "var(--ink-400)",
          500: "var(--ink-500)",
          600: "var(--ink-600)",
          700: "var(--ink-700)",
          800: "var(--ink-800)",
          900: "var(--ink-900)",
        },
        // Paper — warm white surfaces
        paper: {
          0:   "var(--paper-0)",
          50:  "var(--paper-50)",
          100: "var(--paper-100)",
          200: "var(--paper-200)",
          300: "var(--paper-300)",
        },
        // Champagne — premium accent
        champagne: {
          50:  "var(--champagne-50)",
          100: "var(--champagne-100)",
          200: "var(--champagne-200)",
          300: "var(--champagne-300)",
          400: "var(--champagne-400)",
          500: "var(--champagne-500)",
        },
        // Semantic signals
        signal: {
          verified: "var(--signal-verified)",
          "verified-bg": "var(--signal-verified-bg)",
          attention: "var(--signal-attention)",
          "attention-bg": "var(--signal-attention-bg)",
          blocked: "var(--signal-blocked)",
          "blocked-bg": "var(--signal-blocked-bg)",
          info: "var(--signal-info)",
          "info-bg": "var(--signal-info-bg)",
        },
        // Pipeline stages
        stage: {
          trigger: "var(--stage-trigger)",
          shield: "var(--stage-shield)",
          data: "var(--stage-data)",
          ai: "var(--stage-ai)",
          sequence: "var(--stage-sequence)",
          logic: "var(--stage-logic)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        data: ["var(--font-data)"],
      },
      fontSize: {
        "display-1": ["var(--text-display-1)", { lineHeight: "var(--leading-tight)" }],
        "display-2": ["var(--text-display-2)", { lineHeight: "var(--leading-snug)" }],
        "h1": ["var(--text-h1)", { lineHeight: "var(--leading-snug)" }],
        "h2": ["var(--text-h2)", { lineHeight: "var(--leading-snug)" }],
        "h3": ["var(--text-h3)", { lineHeight: "var(--leading-normal)" }],
        "h4": ["var(--text-h4)", { lineHeight: "var(--leading-normal)" }],
        "body": ["var(--text-body)", { lineHeight: "var(--leading-relaxed)" }],
        "body-sm": ["var(--text-body-sm)", { lineHeight: "var(--leading-relaxed)" }],
        "caption": ["var(--text-caption)", { lineHeight: "var(--leading-normal)" }],
        "micro": ["var(--text-micro)", { lineHeight: "var(--leading-normal)" }],
        "eyebrow": ["var(--text-eyebrow)", { lineHeight: "var(--leading-normal)" }],
      },
      spacing: {
        "1": "var(--space-1)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "7": "var(--space-7)",
        "8": "var(--space-8)",
        "9": "var(--space-9)",
        "10": "var(--space-10)",
        "11": "var(--space-11)",
        "12": "var(--space-12)",
        "14": "var(--space-14)",
        "16": "var(--space-16)",
        "20": "var(--space-20)",
        "24": "var(--space-24)",
        "28": "var(--space-28)",
        "gutter": "var(--layout-gutter)",
        "sidebar": "var(--layout-app-sidebar)",
        "topbar": "var(--layout-topbar)",
      },
      maxWidth: {
        "layout": "var(--layout-max)",
      },
      borderRadius: {
        "xs": "var(--radius-xs)",
        "sm": "var(--radius-sm)",
        "md": "var(--radius-md)",
        "lg": "var(--radius-lg)",
        "xl": "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "pill": "var(--radius-pill)",
      },
      boxShadow: {
        "hairline": "var(--shadow-hairline)",
        "card": "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        "raised": "var(--shadow-raised)",
        "overlay": "var(--shadow-overlay)",
        "action": "var(--shadow-action)",
        "action-accent": "var(--shadow-action-accent)",
        "focus": "var(--focus-ring)",
        "glow-accent": "var(--glow-accent)",
        "glow-champagne": "var(--glow-champagne)",
      },
      transitionTimingFunction: {
        "standard": "var(--ease-standard)",
        "entrance": "var(--ease-entrance)",
        "exit": "var(--ease-exit)",
      },
      transitionDuration: {
        "instant": "var(--duration-instant)",
        "fast": "var(--duration-fast)",
        "base": "var(--duration-base)",
        "slow": "var(--duration-slow)",
      },
    },
  },
  plugins: [],
};

export default config;
