"use client";

import { useState } from "react";

interface OutputsViewProps {
  palOutput: Record<string, unknown> | null;
  projectId: string | null;
}

type Tab = "n8n" | "skill" | "guide" | "email" | "prompts";

interface PushResult {
  success:     boolean;
  workflowId?: string;
  workflowUrl?:string;
  nodeCount?:  number;
  name?:       string;
  message?:    string;
  error?:      string;
}

export default function OutputsView({ palOutput, projectId }: OutputsViewProps) {
  const [activeTab, setActiveTab] = useState<Tab>("n8n");
  const [copied,    setCopied]    = useState<string | null>(null);
  const [pushing,   setPushing]   = useState(false);
  const [pushResult,setPushResult]= useState<PushResult | null>(null);

  const tabs: { id: Tab; label: string; icon: string; desc: string }[] = [
    { id: "n8n",     label: "n8n Workflow",    icon: "⚡", desc: "Import-ready JSON" },
    { id: "skill",   label: "Skill Definition", icon: "✦", desc: "Claude agent config" },
    { id: "guide",   label: "Deploy Guide",     icon: "📖", desc: "Setup instructions" },
    { id: "email",   label: "Email Framework",  icon: "✉️", desc: "PAS template" },
    { id: "prompts", label: "Build Prompts",    icon: "💬", desc: "Customization prompts" },
  ];

  const getContent = (tab: Tab): string => {
    if (!palOutput) return "";
    switch (tab) {
      case "n8n":     return (palOutput.n8nWorkflowJson as string) || "// No workflow generated yet";
      case "skill":   return (palOutput.skillDefinition as string) || "No skill definition yet";
      case "guide":   return (palOutput.deployGuide as string) || "No guide generated yet";
      case "email":   return (palOutput.emailFramework as string) || "No email framework yet";
      case "prompts": return (palOutput.buildPrompts as string) || "No build prompts yet";
    }
  };

  const copy = async (text: string, id: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const download = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const pushToN8n = async () => {
    const n8nUrl    = localStorage.getItem("ppal_n8n_url")  || "";
    const n8nApiKey = localStorage.getItem("ppal_n8n_key")  || "";
    if (!n8nUrl || !n8nApiKey) {
      alert("Set your n8n URL and API key in Integrations first.");
      return;
    }
    const workflowJson = getContent("n8n");
    if (!workflowJson || workflowJson.startsWith("//")) {
      alert("Generate a workflow first.");
      return;
    }
    setPushing(true); setPushResult(null);
    try {
      const res  = await fetch("/api/n8n/push", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ n8nUrl, n8nApiKey, workflowJson, workflowName: "Prospect PAL Workflow" }),
      });
      const data = await res.json() as PushResult;
      setPushResult(data);
    } catch {
      setPushResult({ success: false, error: "Network error — please try again" });
    } finally {
      setPushing(false);
    }
  };

  if (!palOutput) {
    return (
      <div style={{ padding: 32, maxWidth: 640, margin: "0 auto" }}>
        <div style={{ background: "white", border: "1px solid #eceae4", borderRadius: 18, padding: 48, textAlign: "center", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" }}>
          <div style={{ fontSize: 40, marginBottom: 16 }}>📦</div>
          <h2 style={{ fontSize: 18, fontWeight: 800, color: "#111", margin: "0 0 8px" }}>No outputs yet</h2>
          <p style={{ fontSize: 14, color: "#6B7280", margin: "0 0 24px" }}>
            Build a workflow in the Builder tab to generate your n8n workflow package.
          </p>
        </div>
      </div>
    );
  }

  const icp = palOutput.icpProfile as Record<string, unknown> | undefined;
  const tools = palOutput.toolStack as Record<string, unknown> | undefined;
  const content = getContent(activeTab);

  return (
    <div className="p-8 max-w-5xl mx-auto">

      {/* ICP Summary */}
      {icp && (
        <div className="bg-white border border-surface-200 rounded-2xl p-5 shadow-card mb-6">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="font-bold text-ink">Your Generated Engine</h2>
              <p className="text-xs text-ink-muted mt-0.5">
                {projectId ? `Project ID: ${projectId}` : "Generated by PAL Pipeline"}
              </p>
            </div>
            <div className="flex gap-2">
              <span className="badge-green">✓ Configured</span>
              <button
                onClick={() => download(JSON.stringify(palOutput, null, 2), "pal-output.json", "application/json")}
                className="btn-outline text-xs"
              >
                ↓ Export All
              </button>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: "Product",    value: (icp.productDescription as string)?.slice(0, 40) + "..." },
              { label: "Industries", value: ((icp.targetIndustries as string[]) || []).join(", ").slice(0, 40) || "—" },
              { label: "Titles",     value: ((icp.targetTitles as string[]) || []).slice(0, 2).join(", ") || "—" },
              { label: "Tool Stack", value: `${tools?.leadSource ?? "—"} → ${tools?.crm ?? "—"} → ${tools?.sequencer ?? "—"}` },
            ].map((item) => (
              <div key={item.label} className="bg-surface-50 border border-surface-100 rounded-xl p-3">
                <div className="text-xs text-ink-muted mb-0.5">{item.label}</div>
                <div className="text-sm font-semibold text-ink leading-tight">{item.value}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab Selector */}
      <div className="flex gap-2 mb-4 overflow-x-auto scrollbar-hide">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-shrink-0 flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all ${
              activeTab === tab.id
                ? "bg-brand-700 text-white shadow-btn-brand"
                : "bg-white border border-surface-200 text-ink-secondary hover:border-surface-300"
            }`}
          >
            <span>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content Panel */}
      <div className="bg-white border border-surface-200 rounded-2xl shadow-card overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-surface-100 bg-surface-50">
          <div className="flex items-center gap-2">
            <span className="text-lg">{tabs.find((t) => t.id === activeTab)?.icon}</span>
            <div>
              <span className="font-semibold text-sm text-ink">{tabs.find((t) => t.id === activeTab)?.label}</span>
              <span className="text-xs text-ink-muted ml-2">— {tabs.find((t) => t.id === activeTab)?.desc}</span>
            </div>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => copy(content, activeTab)}
              className="btn-ghost text-xs"
            >
              {copied === activeTab ? "✓ Copied" : "Copy"}
            </button>
            <button
              onClick={() => download(
                content,
                activeTab === "n8n" ? "prospect-pal-workflow.json" : `prospect-pal-${activeTab}.md`,
                activeTab === "n8n" ? "application/json" : "text/markdown"
              )}
              className="btn-brand text-xs px-3 py-1.5"
            >
              ↓ Download
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="overflow-auto" style={{ maxHeight: "480px" }}>
          <pre className="p-5 text-xs leading-relaxed text-gray-200 bg-gray-950 font-mono whitespace-pre-wrap">
            {content || "// Output will appear here after generation"}
          </pre>
        </div>
      </div>

      {/* Push to n8n — shown when on the n8n tab */}
      {activeTab === "n8n" && (
        <div style={{
          marginTop: 16, background: "white",
          border: "1px solid #eceae4", borderRadius: 14,
          padding: "18px 22px", boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <div style={{ width: 36, height: 36, borderRadius: 10, background: "#ff6d5a18", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 }}>⚡</div>
              <div>
                <div style={{ fontSize: 13, fontWeight: 700, color: "#111" }}>Push to n8n Workspace</div>
                <div style={{ fontSize: 12, color: "#6B7280" }}>Deploy this workflow directly into your n8n canvas — no copy-paste</div>
              </div>
            </div>
            <button
              onClick={pushToN8n}
              disabled={pushing}
              style={{
                padding: "10px 22px", fontSize: 13, fontWeight: 700,
                color: "white", background: pushing ? "#2d762d" : "#1c5a1c",
                border: "none", borderRadius: 10, cursor: pushing ? "not-allowed" : "pointer",
                display: "flex", alignItems: "center", gap: 8, fontFamily: "inherit",
                boxShadow: "0 2px 8px rgba(28,90,28,0.25)", whiteSpace: "nowrap" as const,
              }}
            >
              {pushing ? <><PushSpinner /> Pushing...</> : "⚡ Push to n8n"}
            </button>
          </div>

          {/* Push result */}
          {pushResult && (
            <div style={{
              marginTop: 14, padding: "12px 16px", borderRadius: 10,
              background: pushResult.success ? "#f0f9f0" : "#fef2f2",
              border: `1px solid ${pushResult.success ? "#bce3bc" : "#fca5a5"}`,
            }}>
              {pushResult.success ? (
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: "#1c5a1c" }}>✓ Workflow pushed!</div>
                    <div style={{ fontSize: 12, color: "#2d762d", marginTop: 2 }}>
                      {pushResult.nodeCount} nodes · {pushResult.name}
                    </div>
                  </div>
                  <a
                    href={pushResult.workflowUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      padding: "8px 16px", fontSize: 12, fontWeight: 700,
                      color: "white", background: "#1c5a1c",
                      borderRadius: 8, textDecoration: "none", whiteSpace: "nowrap" as const,
                    }}
                  >
                    Open in n8n →
                  </a>
                </div>
              ) : (
                <div style={{ fontSize: 13, color: "#dc2626" }}>✗ {pushResult.error}</div>
              )}
            </div>
          )}
        </div>
      )}

      {/* PAL Stage Timeline */}
      {Array.isArray(palOutput.palStages) && palOutput.palStages.length > 0 && (
        <div className="mt-6 bg-white border border-surface-200 rounded-2xl p-5 shadow-card">
          <h3 className="font-bold text-ink mb-4">PAL Pipeline Trace</h3>
          <div className="space-y-3">
            {(palOutput.palStages as { stage: number; name: string; description: string; duration: number }[]).map((stage) => (
              <div key={stage.stage} className="flex items-start gap-3">
                <div className="w-6 h-6 rounded-full bg-brand-700 text-white text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                  {stage.stage}
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-sm text-ink">{stage.name}</span>
                    <span className="text-xs text-ink-muted">{(stage.duration / 1000).toFixed(1)}s</span>
                  </div>
                  <p className="text-xs text-ink-secondary mt-0.5">{stage.description}</p>
                </div>
                <span className="text-emerald-500 text-sm">✓</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function PushSpinner() {
  return (
    <span style={{
      width: 13, height: 13,
      border: "2px solid rgba(255,255,255,0.3)", borderTopColor: "white",
      borderRadius: "50%", display: "inline-block",
      animation: "spin 0.7s linear infinite",
    }} />
  );
}
