"use client";

import { useState } from "react";
import { Button, Card, Badge, Icon } from "@/components/ds";
import { Download, Upload, Check, ExternalLink } from "lucide-react";

interface Deliverable {
  file: string;
  badge: string;
  label: string;
  description: string;
  ready: boolean;
}

const DELIVERABLES: Deliverable[] = [
  { file: "workflow.n8n.json", badge: "Import ready", label: "Production workflow", description: "Nine wired nodes with error catchers, expressions and sub-workflow hooks.", ready: true },
  { file: "workflow.make.json", badge: "Make.com", label: "Make scenario", description: "Equivalent workflow for Make (Integromat) platform.", ready: false },
  { file: "workflow.gumloop.json", badge: "Gumloop", label: "Gumloop workflow", description: "Equivalent workflow for Gumloop automation.", ready: false },
  { file: "BUILD_PROMPT.md", badge: "Documentation", label: "Deploy checklist", description: "Every credential and ENV var still to wire, in the order you'll need them.", ready: true },
  { file: ".env.template", badge: "Security", label: "Zero hard-coded secrets", description: "Providers referenced by ENV name only — no key ever leaves your browser.", ready: true },
  { file: "email-framework.md", badge: "Copywriting", label: "3-sentence PAS scripts", description: "Problem-agitate-solve templates with dynamic variable mappings.", ready: true },
  { file: "PRD.md", badge: "Strategy", label: "Pipeline specification", description: "ICP matrix, data dictionary, bounce guardrails and compliance rules.", ready: true },
  { file: "ack.json", badge: "API contract", label: "Compile receipt", description: "Run status, resolved bindings and every requires_connection flag.", ready: true },
];

export default function OutputsView() {
  const [deployTarget, setDeployTarget] = useState("");
  const [isDeploying, setIsDeploying] = useState(false);
  const [deployed, setDeployed] = useState(false);

  const handleDeploy = async () => {
    if (!deployTarget) return;
    setIsDeploying(true);
    await new Promise((resolve) => setTimeout(resolve, 2000));
    setIsDeploying(false);
    setDeployed(true);
  };

  const handleDownload = (file: string) => {
    const content = file.endsWith(".json") ? JSON.stringify({ name: "Prospect PAL Workflow", nodes: [] }, null, 2) : `# ${file}\n\nGenerated by Prospect PAL`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = file;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ height: "100%", overflowY: "auto", padding: "26px 32px 40px" }}>
      <div style={{ maxWidth: 900, margin: "0 auto" }}>
        {/* Header */}
        <div style={{ marginBottom: 28 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
            <h1
              style={{
                margin: 0,
                fontFamily: "var(--font-display)",
                fontSize: "var(--text-h1)",
                fontWeight: "var(--weight-bold)",
                letterSpacing: "var(--tracking-display)",
              }}
            >
              Outputs & deploy
            </h1>
            <Badge tone="brand" icon="Package">6 files ready</Badge>
          </div>
          <p style={{ margin: 0, fontSize: "var(--text-body-sm)", color: "var(--text-secondary)" }}>
            Download your compiled workflow or deploy directly to your automation instance.
          </p>
        </div>

        {/* Deploy Section */}
        <Card padding="lg" style={{ marginBottom: 24 }}>
          <div
            style={{
              fontSize: "var(--text-eyebrow)",
              fontWeight: "var(--weight-semibold)",
              textTransform: "uppercase",
              letterSpacing: "var(--tracking-eyebrow)",
              color: "var(--text-brand)",
              marginBottom: 12,
            }}
          >
            Direct deploy
          </div>
          <div style={{ display: "flex", gap: 12, alignItems: "flex-end" }}>
            <div style={{ flex: 1 }}>
              <label
                style={{
                  display: "block",
                  fontSize: "var(--text-body-sm)",
                  fontWeight: "var(--weight-semibold)",
                  color: "var(--text-secondary)",
                  marginBottom: 6,
                }}
              >
                n8n instance URL
              </label>
              <input
                type="url"
                value={deployTarget}
                onChange={(e) => setDeployTarget(e.target.value)}
                placeholder="https://your-instance.n8n.cloud"
                style={{
                  width: "100%",
                  padding: "10px 14px",
                  fontSize: "var(--text-body-sm)",
                  fontFamily: "var(--font-data)",
                  borderRadius: "var(--radius-md)",
                  border: "1.5px solid var(--border-hairline)",
                  outline: "none",
                }}
              />
            </div>
            <Button
              variant="accent"
              icon={deployed ? "Check" : "Upload"}
              onClick={handleDeploy}
              disabled={!deployTarget || isDeploying || deployed}
            >
              {deployed ? "Deployed" : isDeploying ? "Deploying..." : "Deploy to n8n"}
            </Button>
          </div>
          {deployed && (
            <div style={{ marginTop: 12, display: "flex", alignItems: "center", gap: 8, fontSize: "var(--text-body-sm)", color: "var(--signal-verified)" }}>
              <Icon name="CircleCheck" size={16} color="var(--signal-verified)" />
              Workflow deployed successfully. Open your n8n instance to activate it.
            </div>
          )}
        </Card>

        {/* Deliverables Grid */}
        <div
          style={{
            fontSize: "var(--text-eyebrow)",
            fontWeight: "var(--weight-semibold)",
            textTransform: "uppercase",
            letterSpacing: "var(--tracking-eyebrow)",
            color: "var(--text-muted)",
            marginBottom: 12,
          }}
        >
          Compiled artifacts
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 12 }}>
          {DELIVERABLES.map((d) => (
            <div
              key={d.file}
              onClick={() => d.ready && handleDownload(d.file)}
              style={{
                padding: "var(--space-9)",
                borderRadius: "var(--radius-xl)",
                cursor: d.ready ? "pointer" : "default",
                border: "1px solid var(--border-hairline)",
                background: "var(--surface-card)",
                boxShadow: "var(--shadow-card)",
                opacity: d.ready ? 1 : 0.6,
                transition: "all 0.15s ease",
              }}
            >
              <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}>
                <div>
                  <Badge tone={d.ready ? "neutral" : "attention"} style={{ marginBottom: 8 }}>
                    {d.badge}
                  </Badge>
                  <div
                    style={{
                      fontFamily: "var(--font-data)",
                      fontSize: "var(--text-body-sm)",
                      color: d.ready ? "var(--text-primary)" : "var(--text-muted)",
                      marginBottom: 4,
                    }}
                  >
                    {d.file}
                  </div>
                  <div style={{ fontSize: "var(--text-caption)", color: "var(--text-secondary)", lineHeight: "var(--leading-relaxed)" }}>
                    {d.description}
                  </div>
                </div>
                {d.ready ? (
                  <Download size={18} strokeWidth={1.75} color="var(--cobalt-500)" style={{ flexShrink: 0 }} />
                ) : (
                  <Badge tone="attention" icon="Clock">Coming soon</Badge>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Security Note */}
        <div style={{ marginTop: 24, display: "flex", alignItems: "flex-start", gap: 10, fontSize: "var(--text-caption)", color: "var(--text-secondary)" }}>
          <Icon name="ShieldCheck" size={16} color="var(--signal-verified)" style={{ flexShrink: 0, marginTop: 1 }} />
          <span>
            All credentials are referenced by ENV name only. No API keys, tokens, or secrets are included in any downloaded file.
            Your workflow runs entirely on your own infrastructure.
          </span>
        </div>
      </div>
    </div>
  );
}
